version: '3.9'

services:
  postgres:
    image: postgres
    container_name: stalk-postgres
    ports:
      - '5436:5432'
    volumes:
      - .:/docker-entrypoint-stalk-initdb.d
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456789'
      POSTGRES_DB: 'stalk-db'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d stalk-db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - stalk-networks

  neo4j:
    image: neo4j:4.4.35
    ports:
      - 7474:7474
      - 7687:7687
    container_name: stalk-neo4j
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test12345
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    networks:
      - stalk-networks

networks:
  stalk-networks:
    driver: bridge
